name: build and deploy Chat App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy chat app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Test
        run: |
          cd chat-app
          mvn -B test --file pom.xml
          cd ..

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push docker images
        run: docker-compose build && docker-compose push